export * from './RegisterTemplate'
export * from './LoginTemplate'
export * from './Account'
export * from './Admin'
export * from './CourseTemplate'
export * from './HomeTemplate'
export * from './DetailKhoaHocTemplate'